### ISSUE TITLE
Implement 2FA in our Discord

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/OMI#230]
Implement 2FA in our Discord

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/229#discussioncomment-2731953_

**Comment by robertlong** [comment]
We just need to turn it back on. Should just be a quick setting to flip.

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/167907052-6d7437f7-5f7e-42a9-a0a2-f72d42559dd4.png)

**Comment by mrmetaverse** [comment]
:heavy_check_mark: 
Implemented 2FA in AngellXR | OMI Discord 

![image](https://user-images.githubusercontent.com/63426722/167907338-adfe87b3-4b44-4afc-84ed-24d0e0ba3f0d.png)
