### ISSUE TITLE
OMI Homepage / Documentation Site

### ISSUE THREAD

**Issue by robertlong** [omigroup/OMI#49]
# OMI Homepage / Documentation Site

## Contributors

- Robert Long

## Summary

OMI has a wide reaching community, particularly within the metaverse creator community. We should create a documentation site for the creation of metaverse media, educating others about the open metaverse, and showcasing projects within the community.

## Example Use Cases

- VRM Avatar Creation Resources
- A directory of current and historical metaverse projects and standards
- Articles about privacy, freedom of expression in the metaverse, and more

## Implementation

I'd like to create a [Docusaurus](https://docusaurus.io) site on https://omigroup.org. Anyone will be able to contribute content to the site via a GitHub repository. We can also ensure that it is searchable and localized. I can do the work of setting it up and automating the publishing process. I need help brainstorming what content should be included on the site. We then need to write and organize it.

I'd like to schedule a separate meeting to brainstorm content for the documentation site. If you're interested in coming to that meeting or would like to participate in some other way, please comment below.

### Update: As of 08/22/21
To add this to your calendar click **[here](https://calendar.google.com/event?action=TEMPLATE&tmeid=NjAzbGlraDFpZWxlcDM2Zjk2b2VqZjEydmIgY18wZHB1Z2Y5ZjgzZXE0cWVrbWI2b21xYmptZ0Bn&tmsrc=c_0dpugf9f83eq4qekmb6omqbjmg%40group.calendar.google.com)** :point_left:

**Comment by matthewbcool** [comment]
I can help. 🙋‍♂️  Brainstorming, maintaining/building/styling the site. Seems like these docs can potentially serve a wide variety of people: developers, designers, artists, ect.  I'll contribute wherever I can.

**Comment by jsealt** [comment]
Related notes from last weeks session: https://hackmd.io/6LzNhWDCT6ito0PjrpnEpQ?edit

**Comment by robertlong** [comment]
Ok so we did the brainstorming session. Thank you everyone who helped out! The next step is to go deeper into the content for the site. What do people's availability look like Tomorrow, Friday, or Tuesday? I'm pretty busy this weekend and Monday.

Also is anyone interested in doing some graphic design for the home page, possibly creating a color scheme, etc?

**Comment by robertlong** [comment]
We'll be meeting to work on the content for the landing page and rest of the site on Tuesday, July 13th at 12:00 PM PDT

[Click here to add it to your calendar](https://calendar.google.com/event?action=TEMPLATE&tmeid=M29tMXVmdm1zMjM1cDFwaXZocDJodGdxZzIgY18wZHB1Z2Y5ZjgzZXE0cWVrbWI2b21xYmptZ0Bn&tmsrc=c_0dpugf9f83eq4qekmb6omqbjmg%40group.calendar.google.com)

**Comment by Elirudite** [comment]
Shadow here, I'd like to help with the UX of this site! Seems like with all this content, we will need a good command of research, content strategy, and information architecture. I am new to the space of UX so this will help me practice, but if anyone is more skilled at UX, I'd of course defer to them.

**Comment by jsealt** [comment]
> Shadow here, I'd like to help with the UX of this site! Seems like with all this content, we will need a good command of research, content strategy, and information architecture. I am new to the space of UX so this will help me practice, but if anyone is more skilled at UX, I'd of course defer to them.

@Elirudite absolutely. By all means, apply your learnings and experiment. We have a number of people experienced in UX who can help, but it all depends on someone breaking the ice. Happy to help or provide review as needed as well!

**Comment by Elirudite** [comment]
Hey, I want to make sure I dont procrastinate on this (and even if my help is needed). I noticed that we were basically creating the website via everyone chipping in ideas. If that is the method you all want to use to build out the site, then perhaps you don't need individual roles? 

But if you do, I think having a deadline + a voluntary role/tasks-needed-doing sort of structure will help keep the ball rolling.

Either way, I think there needs to be more clarity on what needs to be done, who will be responsible for it, and when it should be done. Otherwise, things are bound to slip under the radar.

**Comment by humbletim** [comment]
@jsealt's 7/21/2021 OMI Weekly Meeting 13 notes: https://hackmd.io/e4RBv8H6TnKfud7ebrvmNQ?both#Website-Effort-49

## Website Effort #49
- Progress so far can be tracked here on issue [#49](https://github.com/omigroup/OMI/issues/49)
- Looking for someone to help take the lead this week, or suggests that we postpone until next week. 
- Evo volunteered to support 
- Shadow proposed that we document on github what we want to do, roles, goals, tasks, etc. 
- Our build script is pretty simple
- Time for the blog next 
- :dart: **goal:** plan a workshop to get the content done for this website 
    - Tuesday or Thursday next week 
    - :calendar: Shooting for Thursday 7/29 at 5pm PDT 
- We are looking to schedule this next week or the week after, as we have about 3 meetings scheduled for this week.

**Comment by robertlong** [comment]
## Notes from today's meeting
- Work continues on content for the landing page
- Drew generated some ideas for one line descriptions of OMI, vision statements, and more
- Shadow worked on a next draft of the information architecture
- We all riffed on more one line descriptions as well as coming up with our voice for the website. Focusing on positive but concise language outlining our goals and vision for the metaverse. Language which is clear enough that it can't be used against our mission because it is baked into it.

[Figma Document](https://www.figma.com/file/7IkelFTsQPpMwzrWGzqFBA/Website)
[HackMD Document](https://hackmd.io/@robertlong/omi-website-content)

**Comment by mrmetaverse** [comment]
The Website team will be meeting today at 1PM EDT to discuss our next iteration.

**Comment by mrmetaverse** [comment]
Live Site: https://omigroup.org/home 

New Repo: https://github.com/omigroup/website 

We will resume work in that repo.

**Comment by mrmetaverse** [comment]
Moving to done. Future work will be be broken out into items on the omigroup/website repo backlog.
