### ISSUE TITLE
Establish Fiscal Development working group

### ISSUE THREAD

**Issue by jsealt** [omigroup/OMI#57]
# Fiscal Development 
In today's OMI [weekly meeting 11](https://github.com/omigroup/OMI/discussions/54) Evo proposed forming a small group for discussing and planning fiscal development for OMI. We have a lot of work to do to establish documentation tactics, potential grants and funders, opportunities for establish best practices with OMI fiscal development. 

If you would like to join this working group please sign up by commenting below :point_down: 

(note to admins: Feel free to re-write my spec here, just getting something out there to collect sign ups from those who expressed interest in participating)

**Comment by fire** [comment]
I want to join the Fiscal Development working group.

**Comment by humbletim** [comment]
@jsealt's excellent meeting notes from 7/21/2021 OMI Week 13 meeting: https://hackmd.io/@mrmetaverse/omi-072121#Fiscal-Development-Group

## Fiscal Development Group 
- We set up issue [#57](https://github.com/omigroup/OMI/issues/57) to plan and form a team to discuss who we can reach out to for grants and resources. 
- We have had some volunteers, and would like to remind the group that anyone else may get involved 
- At present moment the group consists of Evo, Jesse, Robert, and Fire. 
- Ways to fund hackathons, methods of promoting the devs in this community, resources for these types of things. 
- Does anyone have connections to metaverse funds? 
- **:dart: goal:** Identify the top 5 groups to apply
- Our next steps include developing our one pager for folks to be able to begin partnering. If we are a community group asking other orgs to support us, are we asking them to support an event, or are we asking them to support the open metaverse at large (paraphrase). 
- This group will be meeting a little later today 
- More information on [Open Funding OS Resources](https://github.com/ralphtheninja/open-funding)

**Comment by jsealt** [comment]
The Fiscal development working group met last night to continue working. Notes can be found on hackmd [Fiscal Development Meeting 7/21/21](https://hackmd.io/@robertlong/omi-fiscal-development)

## Potential Projects to Fund

- glTF Blender Addon
    - Original funding has ran out
    - Work with Blender Foundation and Khronos to increase funding to this project
- Interoperable Art Day
    - Encourage artists to build glTF environments / avatars / props / experiences that can be used for interoperability experiments, the OMI home space etc.
    - Determine pain points in glTF tooling and get feedback from artists
    - OMI can provide support and community for artists during the event
    - Use funding for awards
- Open Marketplace
    - Icosa: https://beta.icosa.gallery/
    - pmndrs market: https://market.pmnd.rs/

## Next Steps

- Lightweight event ~1 month from now
    - OMI Demo Day
    - Possibly taking place in Jel
        - Pros:
            - High room capacity
            - Screen sharing
        - Cons:
            - Voxelized glTFs for artists
            - Hopping between experiences lets users see them first hand
        - August 19th or August 26th
- Larger event in October
    - Art Day / Hackathon
- Start conversation with first possible sponsors
    - Prerequisites:
        - OMI Website
        - Send letter of inquiry
- OMI Slide Deck
    - For meetups
    - Presentations for possible donors

**Comment by jsealt** [comment]
In the teams meeting yesterday, the group discussed getting started with Demo days #59 
with initial dates set to be either Aug 19th or Aug 26th
