### ISSUE TITLE
OMI glTF Extensions

### ISSUE THREAD

**Issue by robertlong** [omigroup/OMI#64]
# OMI glTF Extensions

## Contributors

- Robert Long
- @fire 

## Summary

glTF has wide adoption in metaverse platforms. It is used for props, environments, and avatars. However, each platform currently specifies common behaviors such as audio emitters, animation playback, colliders, and more in different ways. In order to make glTF content richer for metaverse applications we propose creating a repository for designing and specifying a set of common glTF extensions.

## Prior Work

In [Mozilla Hubs](https://hubs.mozilla.com/) glTF files contain all of the data needed to specify a scene, object, or avatar. These include components for audio, physics, animations, interactable objects, spawn points, embedded media, and much more.

Hubs based apps such as [Immers Space](https://immers.space) and others have implemented their own custom glTF extensions for their apps as well.

Mozilla has tooling such as the [Spoke](https://hubs.mozilla.com/spoke) editor and [Hubs Blender Exporter](https://github.com/MozillaReality/hubs-blender-exporter) that can be used to add this custom extension data to glTF scenes.

## Technical Overview

Currently the Hubs glTF extensions are not formally specified. Ideally, a subset of these extensions can be identified that are portable to a wide variety of applications. We will create formal specifications in a separate OMI repository following the same OMI specification process. We can also include conformance tests, links to implementations of each specification, and tooling to generate assets with the extension data.

I would like to work on a Three.js implementation of GLTFLoader plugins for these extensions as well as a new Blender addon that can be used to author glTF assets with this extension data.

The next steps for this effort after approval would be to create a GitHub repository where we can author these specifications. It should follow the same process as the [Khronos glTF extension process](https://github.com/KhronosGroup/glTF/tree/master/extensions#creating-extensions). Ideally we can work closely with the Khronos 3D Formats Working Group to identify multi-vendor or KHR extensions to propose to the group. In the interim, I'd like to propose registering a `OMI` vendor prefix for us to use for our draft extensions.

Specifications will be authored in JSON Schema which will define JSON structure and a Markdown document will describe the implementation and properties in detail. Each extension should have multiple implementations before it is approved as an OMI vendor extension. At any point we can determine if there is a broader need for this extension in the glTF community and propose it as an `EXT` or `KHR` extension in the Khronos 3D Formats Working Group.

**Comment by fire** [comment]
I and Robert discussed that a key bugfix on the spec is that extension should be independent and not in a singular OMI-extension. Instead, it should be extracted to be independent extensions like OMI-audio-emitter and OMI-audi-colliders.

We need to also register the OMI namespace in glTF2 Khronos working group.

The Blender extension can be something basic. We can use the Mozilla Hubs Blender exporter as a base.

Ubisoft Mixer is a collaborative tool that is libre in the same spirit. https://github.com/ubisoft/mixer

Will get the CLA legal work setup soon.

**Comment by RangerMauve** [comment]
I'd be interested in participating in this and maybe implementing some of these extensions in Godot and [HyperGodot](https://github.com/RangerMauve/hypergodot/)

**Comment by robertlong** [comment]
Our first meeting for this sub-group will be tomorrow, July 15th at 5PM PDF in the AngellXR Discord.

**Comment by RangerMauve** [comment]
Is there a calendar invite I can subscribe to?

**Comment by fire** [comment]
This proposal has been ratified and work has started!

**Comment by jsealt** [comment]
> "This proposal has been ratified and work has started" 
New repo started: https://github.com/omigroup/gltf-extensions
