### ISSUE TITLE
Team working agreement/playbook Template

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/OMI#68]
Working Agreements / Playbooks are another word for agile team working agreement which we co-create to define how we will work together and respect each other. Note: For those unfamiliar with working agreements, this is not a legal document. 

- howto: [team Canvas workshop](https://dzone.com/articles/kick-off-your-agile-team-with-a-working-agreement-1)
- [example 1](http://www.icrowds.net/wp-content/uploads/2013/04/MSColleaguePrinciples.pdf)
- [example 2 Tezos Agora](https://forum.tezosagora.org/faq#civilized)

This is an example of a working agreement template:
![](https://i.imgur.com/ObuTOs9.png)

**Comment by mrmetaverse** [comment]
I will suggest that as teams form, they can decide how they will work. These topics are covered in team working agreements. The gltf working group may have different ceremonies (daily standup, bi-weekly refinement, bi-weekly retro) than the fiscal development group (kanban, weekly sync). 

If your team needs help creating a working agreement, this template is a one hour workshop, that can help cut through the bs and anxieties associated with making teamwork work. 

Creating a working agreement may be difficult to do for the entire OMI group. I will cancel that suggestion, and instead make myself available to teams to get started. 

To test, I would like to identify a team to pilot the working agreements process.

**Comment by mrmetaverse** [comment]
## Update: If your team would like to implement a team working agreement (it's fun, and effective) please reach out to me :wave:

**Comment by mrmetaverse** [comment]
We are set to test our first working agreement process with the gLTF working group. We will set a future date and share here, and on discord. 

Let's try out this format: 
- Communication Norms 
- Communication Tools 
- Ceremonies  

This should only take about 30-45 minutes. (Let's plan for an hour)

**Comment by mrmetaverse** [comment]
Update: I am migrating from Mural to figjam. The gLTF working group agreement can be found on [figjam by figma](https://www.figma.com/file/ns8eBTPfq330lZR3DfsOvD/OMI-gLTFgroup-WorkingAgreement?node-id=0%3A1)

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/139703204-f85bfe57-c9c1-40bc-8a0f-8f181c52896d.png)

**Comment by mrmetaverse** [comment]
New working agreement template to consider: https://docs.google.com/document/d/14wmoekbULq3XITBRA6w2o8Fpd5jquLxWbnLKqlDhyKA/edit?usp=sharing

**Comment by ornalabs** [comment]
@mrmetaverse Thank you so much for providing a more concise way to form a more open group to workin on project, we will be using this template as foundation of group of 3D artists, Developers and PMs.

**Comment by mrmetaverse** [comment]
> @mrmetaverse Thank you so much for providing a more concise way to form a more open group to workin on project, we will be using this template as foundation of group of 3D artists, Developers and PMs.

Awe thanks a lot, this just made my day. Keep going!! You've got this.

**Comment by mrmetaverse** [comment]
![5EF4F3CF-9307-46A1-9112-1B4415E28C3A-1024x1024.jpg](https://user-images.githubusercontent.com/63426722/147975519-ec728c43-f614-421c-b4be-b6dc6c339a69.jpg)

Shared with me today

**Comment by mrmetaverse** [comment]
Helpful tips for working agreements from Fearless: 
![image](https://user-images.githubusercontent.com/63426722/151670107-98cd57ed-91c8-4f3d-b599-7fc9b924d78b.png)

Read more [on the fearless website](https://fearless.tech/playbooks/team-working-agreements)

**Comment by mrmetaverse** [comment]
the ultra light version:

If you want to go super light here, and only hit the critical things needed to get started, just copy and paste this into your working groups discussions, and ensure it can be accessed by anyone in the group through github. 




```
## Team Norms
_Team Norms are explicit agreements on how we’ll behave together and what we’ll do if an agreement is broken. It’s everyone’s responsibility to set and uphold these agreements, but it’s truly the Team Leader’s role to ensure the team lives by these norms._

## 1. Team Ground Rules 
How do we want to treat each other? (Try to keep the list to the most essential 3-5.)
Rule #1: 
Rule #2:
Rule #3:

_### Examples (delete all of this after)_
_Always assume everyone has the best intent_
_We conduct routine retrospectives to air out the good, the bad, and the improvable to avoid resentment, isolation, or conflict._
_Be on time!_  
_If you’re going to be late, post in the team discord channel to let the team know (be accountable)_

## 2. When we meet / Ceremonies 
Recurring meeting day and cadence: 
Demo days: 
Retrospective: 

_Examples remove any that don't fit your working group or that you do not want_ 

- Daily standup - discord check in 
- Sprint Review - have sprint review prep (last day of the sprint for 15 min)
sprint review/checklist will be created in Confluence
- **Sprint Retros - anonymous entries, but able to own it if you want be open, honest and respectful to your teammates**
- Sprint Planning - this should be capacity and velocity planning with PREVIOUSLY groomed stories from our backlog
- Grooming

## 3. Keeping Ourselves Accountable
Now that we have our norms, how will we hold ourselves accountable? What will we do if we see ourselves or someone else break a rule?
Method 1:
Method 2:

_Ideas: (delete after you decide on yours)_
_We chat in discord, but we track efforts on our github backlog_
_Discord bot to send a prompt to remind group members with omi-chan role of upcoming meetings_
_Simple Google form survey every 4 weeks to rate ourselves on a scale of 1 to 5, and suggest improvements (maybe instead of a actual proper retro, but I still recommend a retro)_ 
_We review our working agreement at every retro._ 


###### Note: The system should flex to your needs, not the other way around. Make sure you adopt processes that fit your needs and availability. There is nothing worse than resentment of process which leads to avoidance and eventually the entire effort fizzling out. We adopt these simple standards to make it easier for folks to get involved, and increase the chances of us finishing the the things we say we will do. Declaring yourself as blocked is not bad! It helps let the rest of the group know that they can help, etc. 
```

**Comment by mrmetaverse** [comment]
Shared by a friend: 

"Some Mural templates that I like are:"

https://app.mural.co/template/de6a02e2-ef53-4996-bac4-12b4d6bbf2bf/df9be646-3cac-4394-8962-d695d0bfffc5

https://app.mural.co/template/53f116d5-db8b-4081-9d05-bd83e79bf068/a4e5fb7a-cb4e-4de7-9c67-5da8549618ea

https://app.mural.co/template/2d72bf3d-d95a-4ae8-b6e0-cd216fcc3f89/cfc57fc1-ac2e-43b9-9801-65d90609cd59

https://app.mural.co/template/61fcc923-d37d-480b-ba87-b2aa0cbf5e9c/2bb1ad49-cb78-4334-8337-e912bb128388

https://app.mural.co/template/bc965c87-b9ae-4429-9c62-a3c1a15cb8d9/c7214d21-ca36-4510-97be-2bc9076bb002
